name: Build VeshuFont

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FontForge
        run: sudo apt-get install -y fontforge python3-fontforge

      - name: Build font
        run: python3 build_font.py

      - name: Commit and push font
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add VeshuFont.ttf
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update VeshuFont.ttf"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
